package com.mycompany.banksystem;

public class DepositMoney extends javax.swing.JFrame {

    public DepositMoney() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accNameNumField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        depositPanel.setBackground(new java.awt.Color(54, 75, 104));
        depositPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Deposit/Logo 2 1.png"))); // NOI18N
        depositPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Deposit/Deposit Button.png"))); // NOI18N
        depositPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        accNameNumField1.setBackground(new java.awt.Color(255, 255, 255));
        accNameNumField1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        accNameNumField1.setForeground(new java.awt.Color(145, 117, 67));
        accNameNumField1.setText("Amount: 100,000.00");
        accNameNumField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 51, 51)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        accNameNumField1.setMargin(new java.awt.Insets(2, 6, 2, 9));
        accNameNumField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                accNameNumField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                accNameNumField1FocusLost(evt);
            }
        });
        depositPanel.add(accNameNumField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 280, 40));

        getContentPane().add(depositPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accNameNumField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accNameNumField1FocusGained
        // TODO add your handling code here:
        if ("Account Name".equals(accNameNumField1.getText())) {
            accNameNumField1.setText("");
        }
    }//GEN-LAST:event_accNameNumField1FocusGained

    private void accNameNumField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accNameNumField1FocusLost
        // TODO add your handling code here:
        if ("".equals(accNameNumField1.getText())) {
            accNameNumField1.setText("Account Name");
        }
    }//GEN-LAST:event_accNameNumField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepositMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepositMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepositMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepositMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepositMoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNameNumField1;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
